version: "3.8"
services:
  db:
    image: postgres:15
    container_name: finance_db
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
