spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance_user
    password: finance_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
